---
- name: Create Prometheus user
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin
    create_home: no

- name: Create directories for Prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus
    - /opt/prometheus

- name: Download Prometheus binary
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.35.0/prometheus-2.35.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0644'

- name: Extract Prometheus files
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/opt/prometheus"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Set ownership for Prometheus files
  file:
    path: "/opt/prometheus"
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes

- name: Symlink Prometheus binaries
  file:
    src: "/opt/prometheus/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - prometheus
    - promtool

- name: Copy Prometheus configuration file
  template:
    src: "prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Copy Prometheus systemd service file
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    mode: '0644'

- name: Reload systemd and start Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
