---
- name: Fetch secrets and deploy
  hosts: localhost
  gather_facts: no
  # become: yes
  vars:
    ansible_python_interpreter: /home/stepan/ansible_azure_venv/bin/python3

  roles:
    - role: fetch_secrets
